### ISSUE TITLE
[Request] Free-form comments for tasks / days

### ISSUE THREAD

**Issue by hackel** [Hoglet/TimeIT#13]
I've been using TimeIT daily for quite a while now and it's been working great for me.  The biggest deficiency it has, in my opinion, is that I have to create a new task for every little thing I want to track, even if it's a one-off thing.  I would love to have the ability to enter some free-form text, either associated with the specific day (this is probably ideal), or the task itself on that day.  I could envision a text-input box in the UI beneath the day/month/week tab box that allows you to enter and save a quick note for the day chosen in the calendar.

**Comment by Hoglet** [comment]
It sounds like some sort of a diary. So you could have a task "Work" and just comment with "Made some bug fixes in the hucklaboo".

I like the idea.

Suggested implementation: 
1. Input box where you can write free text. The entry gets an automated time stamp.
2. A context entry in calendar where you can enter comment on past/future day with optional time of day (defaults to 12:00).
3. Diary entries shown in summaries. (might be crowded in month and year view)
4. Sync with TimeIT server
5. Display on appropriate places in TimeIT server.
6. Input in TimeIT server
