### ISSUE TITLE
[Request] Add time budgets for projects

### ISSUE THREAD

**Issue by tuxflo** [Hoglet/TimeIT#15]
It would be nice if one can add a certain amount of time for a project to see if there is a difference between the estimated time and the real spent time (target-actual comparison).
This could improve the time estimating for projects.

**Comment by Hoglet** [comment]
This sounds like project management or possibly issue tracking, both is out of scope for TimeIT. 

In the far future I could imagine a connection with, for instance, bugzilla to exchange information. Say automatically get tasks into TimeIT from bugzilla and send time data back to it. I also consider it to be better to do that through TimeIT-Server or a freely standing intermediate program.
