### ISSUE TITLE
deleted task continues apearing and working in applet contextmenu

### ISSUE THREAD

**Issue by bits-fritz** [Hoglet/TimeIT#18]
first to say: I'm happy having found timeit - exactly doing what I want :o))

Started with testing task "Kaffeetrinken" subtask "Telefonieren" which both are
obsolete.
- deleted task tree "Kaffeetrinken" from list:
  disappeared as expected
- right clicked taskbar icon:
  Tasks Kaffeetrinken, Kaffeetrinken / Telefonieren are both present and
  working!
- main window:
  summary tile shows deleted task(s), task list doesn't.

screenshot attached.

regards Friedrich

**Comment by bits-fritz** [comment]
didn't succeed to edit issue nor attaching screenshot :-( 
might catch it here:
http://bits-fritz.de/eigene_webdateien/Image/bug-image/timeIT-main-window_2016-08-10_15-14-34-fs8.png

**Comment by bits-fritz** [comment]
didn't succeed to edit issue nor attaching screenshot :-( 
might catch it here:
http://bits-fritz.de/eigene_webdateien/Image/bug-image/timeIT-main-window_2016-08-10_15-14-34-fs8.png

**Comment by bits-fritz** [comment]
didn't succeed to edit issue nor attaching screenshot :-( 
might catch it here:
http://bits-fritz.de/eigene_webdateien/Image/bug-image/timeIT-main-window_2016-08-10_15-14-34-fs8.png

**Comment by bits-fritz** [comment]
didn't succeed to edit issue nor attaching screenshot :-( 
might catch it here:
http://bits-fritz.de/eigene_webdateien/Image/bug-image/timeIT-main-window_2016-08-10_15-14-34-fs8.png

**Comment by bits-fritz** [comment]
didn't succeed to edit issue nor attaching screenshot :-( 
might catch it here:
http://bits-fritz.de/eigene_webdateien/Image/bug-image/timeIT-main-window_2016-08-10_15-14-34-fs8.png

**Comment by Hoglet** [comment]
Thank you for the report. I have confirmed that the same behaviour exists in the latest version.
