### ISSUE TITLE
Idle detection doesn't work in CentOS 8 Stream (Wayland / gnome)

### ISSUE THREAD

**Issue by srguiwiz** [Hoglet/TimeIT#22]
TimeIT app runs, but idle detection is not functional.  Tried many different ways.

Installed with `cmake . && make && sudo make install` .  For prerequisites see comment at issue #21 .

First tried `2.0.X`, which was `2.0.1`, now running branch `master`.  In between cleaning with `git clean -d -f -x`.

Also, tried various configurations of the desktop.  That can be switched by the gear button when logging in.  Default was Standard Wayland.  But also tried Standard X11, and Classic X11.  CentOS 8 Stream is "the new RHEL 8" now.

If there were something simple I can do to debug this, I might try.  Have been looking e.g. at `IdleDetector.cpp` but don't have enough experience yet to really know how this implementation is supposed to work or how to debug.

**Comment by Hoglet** [comment]
TimeIT is using the xscreensaver library to get information if system is idle. This is probably in turn dependant on X11. This would explain why it does not work in Wayland as it is not X11.  Maybe it will work if the compatibility is extended.

Why it does not work when actually running X11 is a different question. Does the screen blank? Is there something inhibiting idle? (like youtube or vlc or something else)

**Comment by srguiwiz** [comment]
The screen blanks.  No YouTube, VLC or anything.  Meanwhile I am getting familiar with `IdleDetector.cpp` by working on issue #23 in Ubuntu 20.04 instead of CentOS 8.

**Comment by Hoglet** [comment]
Idle detection does work in CentOS 8 stream when running xfce4 under X11. This indicates that it is an issue with Wayland and/or the window manager in gnome.

**Comment by Hoglet** [comment]
Idle detection is working in Gnome-shell when running in X11.
Gnome-shell is only reporting one workspace though, probably a gnome bug (it based on Mutter which have had such bug before)

When running under Wayland then TimeIT is closing down as Wayland does not have the XScreenSaverQueryExtension.

TimeIT exits with: 
"Unable to detect if user is idle. XScreenSaverQueryExtension not available"

**Comment by Hoglet** [comment]
Tested KDE and got full functionality (they still have the system tray, yay!)

So full functionality in CentOS 8 Stream with:
* KDE
* XFCE4

Partial functionality:
* gnome-shell

**Comment by Hoglet** [comment]
Code (in python) for idle detection:
https://github.com/escaped/idle_time

**Comment by Hoglet** [comment]
Closing this issue in favour of #47
