### ISSUE TITLE
doesn't build on Archlinux /usr/bin/ld: cannot find -lThreads::Threads

### ISSUE THREAD

**Issue by bits-fritz** [Hoglet/TimeIT#54]
make throws following errors:
`Linking CXX executable tests`
`/usr/bin/ld: cannot find -lThreads::Threads`
`collect2: error: ld status 1` (translated)
`make[2]: *** [tests/CMakeFiles/tests.dir/build.make:468: tests/tests] Fehler 1`
`make[1]: *** [CMakeFiles/Makefile2:366: tests/CMakeFiles/tests.dir/all] Fehler 2`
`make: *** [Makefile:156: all] Fehler 2`

Sorry, by all means couldn't convince make to spit errors in english.

binutils 2.36.1

ready to answer more questions

**Comment by Hoglet** [comment]
It can be missing requirement. It is missing the pthread library.
Try to install libpthread-dev:
https://aur.archlinux.org/packages/libpthread-stubs/
