### ISSUE TITLE
archlinux: wrong path for shared files

### ISSUE THREAD

**Issue by bits-fritz** [Hoglet/TimeIT#55]
refuses to start without manual intervention.
After building the package from the aur (https://aur.archlinux.org/packages/timeit-git/) timeit refuses to start.
Everything is installed in /usr/local/ but shared files are searched in /usr/share/ instead of /usr/local/share.
Softlinking /usr/local/share/timeit at /usr/share/ fixes the issue.

**Comment by Hoglet** [comment]
https://aur.archlinux.org/packages/timeit-git/ and building in arch is not maintained by me. A report to their bug tracker might be appropriate.

That said I will try to help you build it:
If you build and install the latest version from https://github.com/Hoglet/TimeIT does the problem persist?

**Comment by bits-fritz** [comment]
Yes, exactly the same issue.
Everything is installed in /usr/local/ but strace complains about some files missing in /usr/share/timeit.
Example:
`openat(AT_FDCWD, "/usr/share/timeit/icon.svg", O_RDONLY) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)`
Tell me what You need to proceed.

P.S.: once upon a time `export LANG=C` made shell answering english - looong time ago. :-((

**Comment by Hoglet** [comment]
I am reproducing the fault in Devuan.

**Comment by Hoglet** [comment]
If problem persists in the aur then maybe @tuxflo is able to help.
If there still is a problem with building from github source then either reopen this or make a new issue.

**Comment by tuxflo** [comment]
Hi! I haven't used TimeIT for a while now but I'm trying to fix the build. For some reason I'm unable to debug the PKGBUILD because CMake is missing `libgmock`. Was this added recently? Do you know which arch package provides the necessary files? I thought it was `gtest` but it isn't.

**Comment by bits-fritz** [comment]
For what it is worth:
makepkg builds fine with the recent PKGBUILD. Installing the application and starting also fine.
To get the recent pkgver I had to add
<pre>
pkgver() {
  cd "${srcdir}/timeit"
  git describe --tag | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}
</pre>
The regex is c&p ;o))

**Comment by Hoglet** [comment]
I have changed to google-test for unit testing. Unit test are also in their own binary.

libgmock is not installed in my environment as far as I can tell.

PKGBUILD is something I do not know anything about.
