### ISSUE TITLE
Build instructions don't work, files don't compile

### ISSUE THREAD

**Issue by intractabilis** [Hoglet/TimeIT#61]
Download release:
```
$ wget https://github.com/Hoglet/TimeIT/archive/refs/tags/2.0.tar.gz
$ tar xf 2.0.tar.gz
```
Per instruction:
```
$ cd TimeIT-2.0
$ mkdir Release
mkdir: cannot create directory ‘Release’: File exists
$ cd Release
$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
/home/user/somepath/TimeIT-2.0
head: cannot open 'debian/changelog' for reading: No such file or directory
/home/user/somepath/TimeIT-2.0/git_version_gen.sh: line 41: src/version.h: No such file or directory
CMake Error at CMakeLists.txt:19 (file):
  file STRINGS file "/home/user/somepath/TimeIT-2.0/version" cannot be read.
```

Alright, I understand you assume that the build should be performed from the workspace root. Compilation fails anyway
```
$ cd TimeIT-2.0
$ cmake .
$ make -j16
[ 18%] Building CXX object src/CMakeFiles/timeit.dir/GUI/AddTime.cpp.o
/home/user/somepath/TimeIT-2.0/src/DB/Task.cpp: In constructor ‘DB::Task::Task()’:
/home/user/somepath/TimeIT-2.0/src/DB/Task.cpp:10:23: error: ‘time’ was not declared in this scope
   10 |         lastChanged = time(0);
      |                       ^~~~
/home/user/somepath/TimeIT-2.0/src/DB/Task.cpp:4:1: note: ‘time’ is defined in header ‘<ctime>’; did you forget to ‘#include <ctime>’?
    3 | #include <stdexcept>
  +++ |+#include <ctime>
    4 | 
/home/user/somepath/TimeIT-2.0/src/DB/Task.cpp: In member function ‘void DB::Task::setName(std::string)’:
/home/user/somepath/TimeIT-2.0/src/DB/Task.cpp:24:23: error: ‘time’ was not declared in this scope
   24 |         lastChanged = time(0);
      |                       ^~~~
```
And errors going on...

**Comment by intractabilis** [comment]
After adding missing include files, it compiles, but doesn't work:
```
$ src/timeit
terminate called after throwing an instance of 'Glib::FileError'
```

**Comment by Hoglet** [comment]
> Alright, I understand you assume that the build should be performed from the workspace root. Compilation fails anyway
No, it should not be built from project root. There is something else at play
   10 |         lastChanged = time(0);
      |                       ^~~~
/home/user/somepath/TimeIT-2.0/src/DB/Task.cpp:4:1: note: ‘time’ is defined in header ‘<ctime>’; did you forget to ‘#include <ctime>’?
    3 | #include <stdexcept>
  +++ |+#include <ctime>
Just for me to understand: What compiler version are you using? (and os/distribution)

**Comment by Hoglet** [comment]
Coincidentaly, I upgraded my OS yesterday and it does not compile for me either.....

**Comment by intractabilis** [comment]
I am a professional software engineer and deal with dozens of open-source projects daily on various OS and Linux distros. Believe me, it has nothing to do with stability of the OS or bugs in CMake. This problem is entirely specific to your particular project.

**Comment by Hoglet** [comment]
I am happy for you.

Please give me what OS you are running and what compiler you are using. 

When I have my cmake issues ironed out I will address the other issues also.

**Comment by intractabilis** [comment]
Manjaro 20
GCC 12.2.0

Btw, the compiler version is in my first post.

**Comment by Hoglet** [comment]
Thank you, sorry for missing that detail.

I have opened an issue (#62 ) for the compile problem. Your other two issues can remain here for the time being.

**Comment by Hoglet** [comment]
> After adding missing include files, it compiles, but doesn't work:
> 
> ```
> $ src/timeit
> terminate called after throwing an instance of 'Glib::FileError'
> ```
After some thought I get to the conclusion that it is not possible to load icons. Did the make install give some error message?

**Comment by Hoglet** [comment]
If you could try building HEAD and see if that works for you, it works on Debian with gcc 12.2. Please continue compile discussions on #62 

I am still having problems with cmake so I can not do the process from scratch myself.

**Comment by intractabilis** [comment]
> > After adding missing include files, it compiles, but doesn't work:
> > ```
> > $ src/timeit
> > terminate called after throwing an instance of 'Glib::FileError'
> > ```
> 
> After some thought I get to the conclusion that it is not possible to load icons. Did the make install give some error message?

Yeah, we can discard this one. I have fixed all the compilation problems myself. After installation, this one went away.

**Comment by Hoglet** [comment]
That sounds good. I appreciate if you could verify if the compile problem still exists for you on HEAD (#62)
