### ISSUE TITLE
[Request] Separate, per-project idle counts

### ISSUE THREAD

**Issue by hackel** [Hoglet/TimeIT#8]
I use one "in office" project to track when I'm here, and I don't want it to respond to the idle timer, only individual projects.  Currently, when the idle timer goes off, I want to "continue" the "in office" project, but "revert and continue" the specific task I'm working on.  Since there's no way to do this, I have to remember to go back and edit the in office task manually.

**Comment by Hoglet** [comment]
I interpret this as a request to have a more advanced idle dialog, or one dialog per task, so that one can tick of each task independently.

**Comment by Hoglet** [comment]
> I interpret this as a request to have a more advanced idle dialog, or one dialog per task, so that one can tick of each task independently.

Obviously not what was requested, 'F' in reading comprehension on my part.
A "quiet"- option on tasks so that they are not stopped while others are is a great idea.

**Comment by Hoglet** [comment]
Closing as it will be implemented by #52
